### ISSUE TITLE
Next Free Worker Incorrect for GLA

### ISSUE THREAD

**Issue by duncanspumpkin** [TheAssemblyArmada/Thyme#177] opened 2020-11-06 07:42 UTC
#### Original game source: game disc (I think)

- Reproducible in the original Generals Zero Hour? No (not tested but confirmed not reproducible in discord)
- Multiplayer affected? Not tested
- Are you using any mods? No

### Issue explanation
When playing as GLA workers that are collecting resources are in the list of free workers. This means that clicking the next free worker button you may end up removing workers from collecting resources. They should not appear in the list of free workers.

### Steps to reproduce the problem
1. Play as GLA build a Supply Depot
2. Build a few workers at the depot
3. Click the free worker button. Notice that its selecting workers from the depot.

**Comment by tomsons26** [comment] 2020-12-07 20:11
Not able to reproduce

**Comment by duncanspumpkin** [comment] 2020-12-07 20:17
Is that after the fix ai branch?

**Comment by jonwil** [comment] 2022-09-24 12:31
I just tested and I am unable to reproduce as of right now. I think we can close this.

**Closed as completed by jonwil** 2022-09-24 12:31 UTC
Labels: bug, no-repro
